config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'ajaxexample', action: :ajaxexample, controller: 'home'
  resources :authors
  resources :bugs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :fname, :lname, :email, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, length: {maximum: 105},
        uniqueness: { case_sensitive: false },
        format: { with: VALID_EMAIL_REGEX }
        
    validates :thumbnail, allow_blank: true, format: {with: 
        %r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'}
        
    has_many :bugs
end

app/models/bug.rb
class Bug < ApplicationRecord
    enum issue_type: [:issue, :enhancement, :feature]
    enum priority: [:low, :medium, :high]
    enum status: [:open, :closed, :monitor]
    
    validates :title, presence: true
    validates :description, presence: true
    
    belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:fname, :lname, :email, :thumbnail)
    end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, :set_statuses, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
    respond_to do |format|
      format.html {render :index}
      format.json {render :json => @bugs.to_json(:include => :author), status: :ok}
      format.xml {render xml: @bugs.as_json}
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    author = Author.find(bug_params[:author_id])
    @bug.build_author(:id => author.id)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :author_id)
    end
    
    def set_statuses
      @issue_types = Bug.issue_types
      @priorities = Bug.priorities
      @statuses = Bug.statuses
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @bugs = Bug.last(5)
    end
    
    def ajaxexample
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.fname %></td>
        <td><%= author.lname %></td>
        <td><%= author.email %></td>
        <td><%= author.thumbnail %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @author.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @author.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @author.thumbnail %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/bugs/_form.html.erb
<%= form_with(model: bug, local: true) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :issue_type %>
    <%= form.select(:issue_type, Bug.issue_types.keys, {selected: @bug.issue_type}, { :class=>'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.select(:priority, Bug.priorities.keys, {selected: @bug.priority}, {:class=>'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select(:status, Bug.statuses.keys, {selected: @bug.status}, {:class=>'form-control'} )%>
  </div>
  
  <div class="form-group">
    <%= form.label :author_id, :class=>'label' %>
    <%= form.select(:author_id, 
        options_for_select(Author.all.collect {|a| ["#{a.fname} #{a.lname}", a.id]},
        selected: (@bug.author ? @bug.author.id : Author.first.id)), {},
        { :class=>'form-control' } )%>
  </div>

  <div class="actions">
    <%= form.submit 'Save', :class=>'btn btn-success' %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<br />
<h1>Editing Bug</h1>
<hr />

<%= render 'form', bug: @bug %>

<%= link_to 'Show', @bug, class: 'btn btn-primary' %> |
<%= link_to 'Back', bugs_path, class: 'btn btn-primary' %>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>


<%= react_component("AllBugs", { name: 'eric', bugs: Hash[@bugs.map { |l| [l.title, [l.description, l.issue_type, l.priority, l.status]] }].to_json }) %>


<hr/>

<h1>Bugs</h1>
<h4>Original Rails version</h4>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Author</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Issue type</th>
      <th scope="col">Priority</th>
      <th scope="col">Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= (bug.author.try { |a| "#{a.fname} #{a.lname}"} || "NA") %></td>
        <td><%= bug.title %></td>
        <td><%= bug.description %></td>
        <td><%= bug.issue_type %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.status %></td>
        <td><%= link_to 'Show', bug, class: 'btn btn-secondary' %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug), class: 'btn btn-secondary' %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path, class: 'btn btn-primary' %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path, class: 'btn btn-secondary' %>

app/views/bugs/show.html.erb
<h4 id="notice"><%= notice %></h4>


<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Author</span>
  </div>
  <input type="text" class="form-control" value="<%= (@bug.author.try { |a| "#{a.fname} #{a.lname}"} || "NA") %>" readonly />
</div>


<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Title</span>
  </div>
  <input type="text" class="form-control" value="<%= @bug.title %>" readonly />
</div>


<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Description</span>
  </div>
  <textarea class="form-control" readonly><%= @bug.description %></textarea>
</div>

<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Issue Type</span>
  </div>
  <input type="text" class="form-control" value="<%= @bug.issue_type %>" readonly />
</div>

<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Priority</span>
  </div>
  <input type="text" class="form-control" value="<%= @bug.priority %>" readonly />
</div>

<div class="input-group w-50 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Status</span>
  </div>
  <input type="text" class="form-control" value="<%= @bug.status %>" readonly />
</div>

<%= link_to 'Edit', edit_bug_path(@bug), class: 'btn btn-primary' %> |
<%= link_to 'Back', bugs_path, class: 'btn btn-secondary' %>

app/views/home/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Bees!</h1>
        <p>anyway, here's some bugs</p>
    </div>
</div>


<% @bugs.each do |bug| %>
    <div class="card w-25">
        <div class="card-header bg-secondary">
            <h5 class="card-title text-white"><%= bug.title %></h5>
            <small class="text-white"><%= (bug.author.try { |a| "#{a.fname} #{a.lname}"} || "NA") %></small>
            <br />
            <small class="text-white"><%= bug.issue_type %>, <%= bug.priority %>, <%= bug.status %></small>
            
        </div>
        <div class="card-body">
            
            
            <p class="card-text"><%= bug.description %></p>
        </div>
        <div class="card-footer">
            <%= link_to 'Show Bug', bug, { :class=>"btn btn-primary" } %>
        </div>
    </div>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugtracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Eric DeSmet's BugTracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="/bugs">Bugs</a></li>
        <li class="nav-item"><a class="nav-link" href="/authors">Authors</a></li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>